KEY_JWT = 'CLAVE PARA GENERAR EL TOKEN' # Debe ser el mismo del backend, en el caso de usarlo
KEY_ENCRYPT = 'CLAVE PARA ENCRIPTAR' # Debe ser el mismo del backend, en el caso de usarlo
MONGO_URI = 'mongodb://localhost:27017/'
EMAIL_DETECTED = 'CORREO QUE ENVIARÁ LAS ALERTAS DE DETECCIÓN DE SPAM, DEBE DE ESTAR CREADO EN EL SERVIDOR DE ZIMBRA'
DOMAIN_SERVER = 'DOMINIO DEL SERVIDOR DE ZIMBRA'
